# Generated by Django 4.1 on 2022-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('user_phone', models.CharField(max_length=13)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=32)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_quantity', models.IntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('stripe_token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderInQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('user_phone', models.CharField(max_length=13)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=32)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_quantity', models.IntegerField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('stripe_token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
