# Generated by Django 4.1 on 2022-08-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='b4Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('user_phone', models.CharField(max_length=13)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=200)),
                ('cart_id', models.IntegerField()),
                ('product_names', models.TextField(max_length=3200)),
                ('product_prices', models.TextField(max_length=320)),
                ('product_quantities', models.TextField(max_length=100)),
                ('paid_amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.RenameField(
            model_name='completeorder',
            old_name='product_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='orderinqueue',
            old_name='product_id',
            new_name='cart_id',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='stripe_token',
        ),
        migrations.RemoveField(
            model_name='orderinqueue',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderinqueue',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderinqueue',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='orderinqueue',
            name='stripe_token',
        ),
        migrations.AddField(
            model_name='completeorder',
            name='product_names',
            field=models.TextField(default='nothing', max_length=3200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='product_prices',
            field=models.TextField(default='none', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='product_quantities',
            field=models.TextField(default='2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinqueue',
            name='product_names',
            field=models.TextField(default='12', max_length=3200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinqueue',
            name='product_prices',
            field=models.TextField(default='2', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinqueue',
            name='product_quantities',
            field=models.TextField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='paid_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderinqueue',
            name='paid_amount',
            field=models.IntegerField(),
        ),
    ]
