# Generated by Django 4.1 on 2022-08-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensions',
            name='address',
            field=models.CharField(default='USA', max_length=200),
        ),
    ]
