# Generated by Django 4.1 on 2022-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220802_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=32)),
                ('text1', models.TextField(max_length=128)),
                ('link1', models.SlugField()),
                ('picture1', models.ImageField(upload_to='menu/static/menu/images/ad')),
                ('title2', models.CharField(max_length=32)),
                ('text2', models.TextField(max_length=128)),
                ('link2', models.SlugField()),
                ('picture2', models.ImageField(upload_to='menu/static/menu/images/ad')),
            ],
        ),
    ]
