# Generated by Django 4.1 on 2022-08-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='session',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
